config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  scope '(:locale)' do
    get '/', to: 'home#index', as: :home, locale: /en|pt-BR/
    get '/cv(/:disposition)', to: 'download#cv', as: :cv, disposition: /attachment|inline/, defaults: { disposition: :attachment }
  end

  get 'sitemap', to: 'home#index', defaults: { format: :xml }

  get 'manifest', to: 'pwa#manifest', defaults: { format: :json }
  get 'service-worker', to: 'pwa#worker', defaults: { format: :js }
  get 'offline', to: 'pwa#offline'

  devise_for :users, path: 'admin', path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }, controllers: { sessions: 'admin/sessions' }

  namespace :admin do
    root 'about#index'

    resources :abouts, controller: :about, path: :about, except: %i[new show]
    resources :educations, except: :show
    resources :skills, except: :show
    resources :work_experiences, except: :show
    resource :user, controller: :user, only: %i[edit update]
    resource :reorder, only: :update, controller: :reorder
  end

  get '404', to: 'errors#not_found'
  get '422', to: 'errors#unacceptable'
  get '500', to: 'errors#internal_error'
end

app/models/work_experience.rb
# frozen_string_literal: true

class WorkExperience < Locatable
  scope :ordered, -> { order(:order) }
  scope :find_for_locale, ->(locale) { ordered.with_locale(locale) }

  validates :company_name, presence: true
  validates :position, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :start_date, presence: true
end

app/controllers/admin/work_experiences_controller.rb
# frozen_string_literal: true

module Admin
  class WorkExperiencesController < CrudController
    # GET /admin/work_experiences
    def index
      @work_experiences = model.with_locale(locale).ordered
      authorize @work_experiences
      @work_experiences = @work_experiences.decorate
    end

    # GET /admin/work_experiences/new
    def new
      @work_experience = model.new
      authorize @work_experience
    end

    # GET /admin/work_experiences/1/edit
    def edit
      authorize @work_experience
    end

    # POST /admin/work_experiences
    def create
      @work_experience = model.new(permitted_attributes(model))
      authorize @work_experience

      if @work_experience.save
        publish(:experience_created, experience: @work_experience)
        redirect_to redirect_path,
                    notice: t(:created, scope: %i[helpers], model: human_model)
      else
        render :new
      end
    end

    # PATCH/PUT /admin/work_experiences/1
    def update
      authorize @work_experience
      if @work_experience.update(permitted_attributes(@work_experience))
        publish(:experience_updated, experience: @work_experience)
        redirect_to redirect_path,
                    notice: t(:updated, scope: %i[helpers], model: human_model)
      else
        render :edit
      end
    end

    # DELETE /admin/work_experiences/1
    def destroy
      @work_experience.destroy
      authorize @work_experience
      publish(:experience_destroyed, experience: @work_experience)
      redirect_to redirect_path,
                  notice: t(:deleted, scope: %i[helpers], model: human_model)
    end

    private

    def redirect_path
      admin_work_experiences_path(locale: @work_experience.locale)
    end
  end
end

app/views/admin/work_experiences/_form.html.erb
<%= simple_form_for([:admin, work_experience]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :company_name %>
    <%= f.input :position %>
    <%= f.input :city %>
    <%= f.input :country, collection: Country.all %>
    <%= f.input :start_date, include_blank: true %>
    <%= f.input :end_date, include_blank: true %>
    <%= f.input :description %>
    <%= f.input :locale %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/work_experiences/_work_experience.html.erb
<div data-id="<%= work_experience.id %>" class="col-md-6 pt-3 item">
  <div class="list-group-item flex-column align-items-start">
    <div class="d-flex justify-content-between pb-2 pt-2">
      <h5 class="mb-1"><%= work_experience.company_name %></h5>
      <small><%= work_experience.start_date %><br /><%= work_experience.end_date %></small>
      <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group">
          <%= link_to t(:edit, scope: %i[helpers]), [:edit, :admin, work_experience], class: 'btn btn-sm btn-outline-primary' %>
          <%= link_to t(:delete, scope: %i[helpers]), [:admin, work_experience], class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
    <%= markdown work_experience.description %>
    <small class="d-block pb-1"><%= About.human_attribute_name(:position) %>: <%= work_experience.position %></small>
    <small class="d-block pb-1"><%= About.human_attribute_name(:city) %>: <%= work_experience.city %></small>
    <small class="d-block pb-1"><%= About.human_attribute_name(:country) %>: <%= work_experience.country_name %></small>
  </div>
</div>

app/views/admin/work_experiences/edit.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2"><%= t(:edit, scope: %i[helpers]) %> <%= @work_experience.company_name %></h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <%= link_to t(:back, scope: %i[helpers]), %i[admin work_experiences], class: 'btn btn-sm btn-outline-secondary' %>
    </div>
  </div>
</div>

<%= render 'form', work_experience: @work_experience %>

app/views/admin/work_experiences/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2"><%= WorkExperience.model_name.human.pluralize %></h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <%= link_to t(:new, scope: %i[helpers]), %i[new admin work_experience], class: 'btn btn-sm btn-outline-secondary' %>
    </div>
  </div>
</div>

<%= render 'admin/shared/notification' %>

<%= render 'admin/shared/tabs', action: :work_experiences %>

<div class="row pt-3 sortable" data-url="<%= admin_reorder_path %>" data-model="<%= WorkExperience.model_name.param_key %>">
  <%= render @work_experiences %>
</div>

app/views/admin/work_experiences/new.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2"><%= t(:new, scope: %i[helpers]) %> <%= WorkExperience.model_name.human %></h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <%= link_to t(:back, scope: %i[helpers]), %i[admin work_experiences], class: 'btn btn-sm btn-outline-secondary' %>
    </div>
  </div>
</div>

<%= render 'form', work_experience: @work_experience %>