config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  scope '(:locale)' do
    get '/', to: 'home#index', as: :home, locale: /en|pt-BR/
    get '/cv(/:disposition)', to: 'download#cv', as: :cv, disposition: /attachment|inline/, defaults: { disposition: :attachment }
  end

  get 'sitemap', to: 'home#index', defaults: { format: :xml }

  get 'manifest', to: 'pwa#manifest', defaults: { format: :json }
  get 'service-worker', to: 'pwa#worker', defaults: { format: :js }
  get 'offline', to: 'pwa#offline'

  devise_for :users, path: 'admin', path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }, controllers: { sessions: 'admin/sessions' }

  namespace :admin do
    root 'about#index'

    resources :abouts, controller: :about, path: :about, except: %i[new show]
    resources :educations, except: :show
    resources :skills, except: :show
    resources :work_experiences, except: :show
    resource :user, controller: :user, only: %i[edit update]
    resource :reorder, only: :update, controller: :reorder
  end

  get '404', to: 'errors#not_found'
  get '422', to: 'errors#unacceptable'
  get '500', to: 'errors#internal_error'
end

app/models/about.rb
# frozen_string_literal: true

class About < Locatable
  validates :job_title, presence: true
  validates :description, presence: true
  scope :find_for_locale, ->(locale) { with_locale(locale).first_or_initialize }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def country_name
    Country.new(country).name
  end
end

app/models/education.rb
# frozen_string_literal: true

class Education < Locatable
  scope :ordered, -> { order(:order) }
  scope :find_for_locale, ->(locale) { ordered.with_locale(locale) }

  validates :course, presence: true
  validates :institution, presence: true
  validates :start_date, presence: true
end

app/models/locatable.rb
# frozen_string_literal: true

class Locatable < ApplicationRecord
  self.abstract_class = true

  scope :with_locale, ->(locale) { where(locale: locale) }

  validates :locale, presence: true
end

app/models/skill.rb
# frozen_string_literal: true

class Skill < Locatable
  scope :random, -> { order(Arel::Nodes::NamedFunction.new('RANDOM', [])) }
  scope :find_for_locale, ->(locale) { random.with_locale(locale) }

  validates :name, presence: true
  validates :value, presence: true,
                    numericality: {
                      greater_than_or_equal_to: 0,
                      less_than_or_equal_to: 100
                    }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable,
         :rememberable,
         :validatable,
         :trackable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :default_locale, presence: true
end

app/models/work_experience.rb
# frozen_string_literal: true

class WorkExperience < Locatable
  scope :ordered, -> { order(:order) }
  scope :find_for_locale, ->(locale) { ordered.with_locale(locale) }

  validates :company_name, presence: true
  validates :position, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :start_date, presence: true
end

app/controllers/admin/crud_controller.rb
# frozen_string_literal: true

module Admin
  class CrudController < AdminController
    include Publisher
    before_action :set_model, only: %i[edit update destroy]

    private

    def instance_variable_name
      model.model_name.singular
    end

    def instance_variable_value
      model.find(params[:id])
    end

    def set_model
      instance_variable_set(
        "@#{instance_variable_name}",
        instance_variable_value
      )
    end
  end
end

app/controllers/admin/user_controller.rb
# frozen_string_literal: true

module Admin
  class UserController < CrudController
    # GET /admin/users/1/edit
    def edit
      authorize @user
    end

    # PATCH/PUT /admin/users/1
    def update
      authorize @user
      if @user.update(permitted_attributes(@user))
        bypass_sign_in(@user)
        redirect_to %i[edit admin user],
                    notice: t(:updated, scope: %i[helpers], model: human_model)
      else
        render :edit
      end
    end

    private

    def set_model
      @user = current_user
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception, except: %i[worker cv]
end

app/controllers/download_controller.rb
# frozen_string_literal: true

class DownloadController < WebsiteController
  def cv
    render pdf: "curriculum-gustavo-cunha-#{I18n.locale.downcase}",
           disposition: params[:disposition],
           show_as_html: params.key?('debug')
  end

  private

  def set_data
    fetch_from_cache('about')
    fetch_from_cache('educations')
    fetch_from_cache('skills')
    fetch_from_cache('work_experiences')
  end
end

app/controllers/errors_controller.rb
# frozen_string_literal: true

class ErrorsController < WebsiteController
  def not_found
    render status: :not_found
  end

  def unacceptable
    render status: :unprocessable_entity
  end

  def internal_error
    render status: :internal_server_error
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < WebsiteController
  before_action :set_flag_links
  before_action :set_menu_links

  private

  def set_data
    super
    fetch_from_cache('educations')
    fetch_from_cache('skills')
    fetch_from_cache('work_experiences')
  end
end

app/controllers/pwa_controller.rb
# frozen_string_literal: true

class PwaController < WebsiteController
end

app/controllers/website_controller.rb
# frozen_string_literal: true

class WebsiteController < ApplicationController
  before_action :set_locale
  before_action :set_data, except: :worker
  before_action :set_flag_links, except: %i[worker cv]
  before_action :set_menu_links, except: %i[worker cv]

  private

  def fetch_from_cache(model)
    result = Rails.cache.fetch("#{I18n.locale}/#{model}") do
      retrieve_data(model)
    end
    instance_variable_set("@#{model}", result)
  end

  def retrieve_data(model)
    data = model.classify.constantize.find_for_locale(I18n.locale).decorate
    return data.to_a if data.is_a?(ActiveRecord::Relation)

    data
  end

  def set_data
    fetch_from_cache('about')
  end

  def set_flag_links
    @flags = flags.map do |flag|
      {
        link: home_path(flag),
        label: flag,
        css_class: ['flag', flag.downcase].join(' ')
      }
    end
  end

  def set_menu_links
    @links = menus.map do |page|
      {
        link: home_path(I18n.locale, anchor: page),
        label: page.to_s
      }
    end
  end

  def flags
    %i[pt-BR en].delete_if { |lang| lang == I18n.locale }
  end

  def menus
    %i[home about experience skills education contact]
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/css_classes_helper.rb
# frozen_string_literal: true

module CssClassesHelper
  def body_class
    [controller_name, I18n.locale.downcase].join(' ')
  end

  def menu_classes(menu)
    classes = %w[nav-link]
    classes << active_class if menu_active?(menu)
    classes.join(' ')
  end

  def tab_classes(locale)
    classes = %w[nav-link border-bottom]
    classes << active_class if locale_active?(locale)
    classes.join(' ')
  end

  private

  def active_class
    'active'
  end

  def menu_active?(menu)
    controller_name.to_sym == menu
  end

  def locale_active?(locale)
    current_locale = (params[:locale] || I18n.locale).to_s
    current_locale == locale.to_s
  end
end

app/helpers/dates_helper.rb
# frozen_string_literal: true

module DatesHelper
  def end_date(date)
    return t(:current, scope: %i[frontend template]) unless date

    l date
  end
end

app/helpers/locale_helper.rb
# frozen_string_literal: true

module LocaleHelper
  def locale_to_language(locale)
    t(locale, scope: %i[i18n])
  end

  def available_locales
    I18n.available_locales - [I18n.locale]
  end

  def spoken_languages
    spoken_languages_list.join(', ')
  end

  private

  def spoken_languages_list
    I18n.available_locales.map { |locale| locale_to_language(locale) }
  end
end

app/helpers/text_helper.rb
# frozen_string_literal: true

module TextHelper
  def markdown(text)
    return '' unless text

    sanitize(Kramdown::Document.new(text).to_html.squish)
  end
end

app/views/admin/shared/_notification.html.erb
<% if notice %>
  <div>
    <p class="alert alert-success"><%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div>
    <p class="alert alert-warning"><%= alert %></p>
  </div>
<% end %>

app/views/admin/shared/_tabs.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to locale_to_language(I18n.locale), [:admin, action], class: tab_classes(I18n.locale) %>
  </li>
  <% available_locales.each do |locale| %>
    <li class="nav-item">
      <%= link_to locale_to_language(locale), [:admin, action, locale: locale], class: tab_classes(locale) %>
    </li>
  <% end %>
</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="<%=I18n.locale%>">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><%= t(:title, scope: %i[frontend helpers]) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= javascript_pack_tag 'admin/application', type: 'application/javascript', defer: true %>
    <%= stylesheet_link_tag 'admin/application', media: 'all', rel: 'stylesheet' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark flex-md-nowrap p-0">
        <%= link_to t(:header, scope: %i[frontend helpers]), admin_root_path, class: 'navbar-brand' %>
        <ul class="navbar-nav d-flex justify-content-end mr-3">
          <li class="nav-item">
            <%= link_to User.model_name.human, %i[edit admin user], class: menu_classes(:user) %>
          </li>
          <li class="nav-item">
            <%= link_to t(:sign_out, scope: %i[devise shared links]), %i[destroy user session], method: :delete, class: 'nav-link' %>
          </li>
        </ul>
      </nav>
    </header>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-dark sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to About.model_name.human, %i[admin abouts], class: menu_classes(:about) %>
              </li>
              <li class="nav-item">
                <%= link_to Education.model_name.human.pluralize, %i[admin educations], class: menu_classes(:educations) %>
              </li>
              <li class="nav-item">
                <%= link_to Skill.model_name.human.pluralize, %i[admin skills], class: menu_classes(:skills) %>
              </li>
              <li class="nav-item">
                <%= link_to WorkExperience.model_name.human.pluralize, %i[admin work_experiences], class: menu_classes(:work_experiences) %>
              </li>
            </ul>
          </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <%= yield %>
        </main>
      </div>
    </div>
    <footer class="footer fixed-bottom bg-dark text-white">
      <div class="container-fluid">
        &copy; <%= Date.today.year %> <%= t(:title, scope: %i[frontend helpers]) %>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie ie6 no-js" lang="<%=I18n.locale%>"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7 no-js" lang="<%=I18n.locale%>"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8 no-js" lang="<%=I18n.locale%>"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9 no-js" lang="<%=I18n.locale%>"> <![endif]-->
<!--[if gt IE 9]><!--><html class="no-js" lang="<%=I18n.locale%>"><!--<![endif]--><head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title><%= t(:title, scope: %i[frontend helpers]) %></title>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': true, rel: 'stylesheet' %>
  <%= javascript_pack_tag 'application', type: 'application/javascript', defer: true %>
  <link rel="manifest" href="manifest.json">
  <%= favicon_link_tag %>
  <%= favicon_link_tag 'icons/apple-icon-57x57.png', rel: 'apple-touch-icon', sizes: '57x57' %>
  <%= favicon_link_tag 'icons/apple-icon-60x60.png', rel: 'apple-touch-icon', sizes: '60x60' %>
  <%= favicon_link_tag 'icons/apple-icon-72x72.png', rel: 'apple-touch-icon', sizes: '72x72' %>
  <%= favicon_link_tag 'icons/apple-icon-76x76.png', rel: 'apple-touch-icon', sizes: '76x76' %>
  <%= favicon_link_tag 'icons/apple-icon-114x114.png', rel: 'apple-touch-icon', sizes: '114x114' %>
  <%= favicon_link_tag 'icons/apple-icon-120x120.png', rel: 'apple-touch-icon', sizes: '120x120' %>
  <%= favicon_link_tag 'icons/apple-icon-144x144.png', rel: 'apple-touch-icon', sizes: '144x144' %>
  <%= favicon_link_tag 'icons/apple-icon-152x152.png', rel: 'apple-touch-icon', sizes: '152x152' %>
  <%= favicon_link_tag 'icons/apple-icon-180x180.png', rel: 'apple-touch-icon', sizes: '180x180' %>
  <%= favicon_link_tag 'icons/android-icon-192x192.png', rel: 'icon', type: 'image/png', sizes: '192x192'  %>
  <%= favicon_link_tag 'icons/favicon-32x32.png', rel: 'icon', type: 'image/png', sizes: '32x32' %>
  <%= favicon_link_tag 'icons/favicon-96x96.png', rel: 'icon', type: 'image/png', sizes: '96x96' %>
  <%= favicon_link_tag 'icons/favicon-16x16.png', rel: 'icon', type: 'image/png', sizes: '16x16' %>
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="<%= asset_url('icons/ms-icon-144x144.png') %>">
  <meta name="theme-color" content="#ffffff">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%=@about.description%>" />
  <!-- Open Graph Tags -->
  <meta property="og:title" content="<%= t(:title, scope: %i[frontend helpers]) %>" />
  <meta property="og:site_name" content="<%= t(:header, scope: %i[frontend helpers]) %>"/>
  <meta property="og:image" content="<%= asset_url('avatar.jpg') %>"/>
  <meta property="og:url" content="<%= home_url(I18n.locale) %>" />
  <meta property="og:description" content="<%= @about.description %>" />
  <meta property="og:type" content="website" />
  <meta property="og:locale" content="<%= I18n.locale %>" />
  <!--google font style-->
  <!--font-family: 'Open Sans', sans-serif;-->
  <%= csrf_meta_tags %>
</head>
<body id="home" class="<%= body_class %>" data-locale="<%= I18n.locale %>">
  <div class="wrapper" id="wrapper">
    <%= render 'header' %>
    <%= yield %>
    <%= render 'footer' %>
  </div>
  <!-- File generated at <%= Time.now %>-->
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="<%=I18n.locale%>">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><%= t(:title, scope: %i[frontend helpers]) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'admin/application', media: 'all', rel: 'stylesheet' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0">
        <%= link_to t(:header, scope: %i[frontend helpers]), root_path, class: 'navbar-brand col-12' %>
      </nav>
    </header>
    <div class="container-fluid">
      <div class="row justify-content-center">
        <main role="main" class="col-md-6 col-lg-6">
          <%= yield %>
        </main>
      </div>
    </div>
    <footer class="footer fixed-bottom bg-dark text-white">
      <div class="container-fluid">
        &copy; <%= Date.today.year %> <%= t(:title, scope: %i[frontend helpers]) %>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/download.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><%= t(:title, scope: %i[frontend helpers]) %></title>
  <%= wicked_pdf_stylesheet_link_tag 'cv/application' %>
</head>
<body>
  <%=yield%>
</body>
</html>